// <auto-generated />
using System;
using AdmissionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdmissionService.Infrastructure.Migrations
{
    [DbContext(typeof(AdmissionDbContext))]
    [Migration("20250522133452_updateSettingsModel")]
    partial class updateSettingsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdmissionService.Domain.Entities.AdmissionProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentAdmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentAdmissionId");

                    b.ToTable("AdmissionPrograms");
                });

            modelBuilder.Entity("AdmissionService.Domain.Entities.AdmissionSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdmissionSeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UniversityAdmissionStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AdmissionSettings");
                });

            modelBuilder.Entity("AdmissionService.Domain.Entities.StudentAdmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdmissionSeasonId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentAdmissions");
                });

            modelBuilder.Entity("AdmissionService.Domain.Entities.AdmissionProgram", b =>
                {
                    b.HasOne("AdmissionService.Domain.Entities.StudentAdmission", "StudentAdmission")
                        .WithMany("AdmissionPrograms")
                        .HasForeignKey("StudentAdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentAdmission");
                });

            modelBuilder.Entity("AdmissionService.Domain.Entities.StudentAdmission", b =>
                {
                    b.Navigation("AdmissionPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
